python dividemix_cifar100n.py \
  --root ./datasets/DATA \
  --output-dir ./output/cifar100n_dividemix_fast \
  --arch-type backbone \
  --backbone wide_resnet_16_4 \
  --epochs 200 \
  --warmup-epochs 10 \
  --batch-size 64 \
  --lr 0.02 \
  --p-threshold 0.5 \
  --T 0.5 \
  --alpha 4.0 \
  --lambda-u 25.0 \
  --lambda-u-ramp 16
